<?php

namespace AppBundle\Repository;

/**
 * UserPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
